import test from 'node:test';
import assert from 'node:assert/strict';
import {INITIAL_HR_RULES,suggestOvertime,intervalsOverlap,calculateTransport,calculateMileage,calculateLongDistance} from '../src/lib/hr-payroll-rules.js';
import {calculatePayslip} from '../src/lib/payroll-policy.js';
const rules={...INITIAL_HR_RULES,fullTransportDays:20};
test('daily rate paid weekly keeps attendance-based basic earnings',()=>assert.equal(calculatePayslip({pay_basis:'Daily rate',daily_rate:2500,days_present:5,overtime_pay:0,unpaid_days:0,salary_advance:0},{},[]).basic,12500));
test('07:00–17:30 suggests 1.5 hours against 07:30–16:30',()=>assert.equal(suggestOvertime({state:'On site',check_in:'07:00',check_out:'17:30'},rules).hours,1.5));
for(const state of ['Absent','On leave'])test(`no OT for ${state}`,()=>assert.equal(suggestOvertime({state,check_in:'07:00',check_out:'17:30'},rules).hours,0));
test('Site and Travel intervals can be adjacent but not overlap',()=>{assert.equal(intervalsOverlap([[420,450],[990,1050]],[[1050,1110]]),false);assert.equal(intervalsOverlap([[420,450]],[[430,490]]),true);});
test('rounding floors hours and respects minimum',()=>{assert.equal(suggestOvertime({state:'On site',check_in:'07:29',check_out:'16:40'},rules).hours,0);});
test('full transport at configured inclusive threshold',()=>assert.equal(calculateTransport(3000,20,'Attendance-prorated amount',rules).amount,3000));
test('transport below threshold prorates 3000 / 25 × 19 = 2280',()=>assert.equal(calculateTransport(3000,19,'Attendance-prorated amount',rules).amount,2280));
test('strict threshold remains separately configurable',()=>assert.equal(calculateTransport(3000,20,'Attendance-prorated amount',{...rules,fullTransportComparison:'More than'}).amount,2400));
test('unconfirmed threshold cannot silently pay full transport',()=>assert.throws(()=>calculateTransport(3000,19,'Attendance-prorated amount',INITIAL_HR_RULES),/configure/));
test('long distance above threshold pays configured allowance',()=>assert.equal(calculateLongDistance(51,rules),500));
test('distance below or equal threshold pays no allowance',()=>{assert.equal(calculateLongDistance(49,rules),0);assert.equal(calculateLongDistance(50,rules),0);});
test('motorcycle reimbursement uses kilometres × rate',()=>assert.equal(calculateMileage({approvedKm:20},rules).total,340));
test('invalid and negative odometers are rejected',()=>{assert.throws(()=>calculateMileage({startOdometer:100,endOdometer:90},rules));assert.throws(()=>calculateMileage({approvedKm:-1},rules));});
test('fixed travel conflicts with mileage unless policy permits',()=>{assert.throws(()=>calculateMileage({approvedKm:20,fixedTravel:true},rules));assert.equal(calculateMileage({approvedKm:20,fixedTravel:true},{...rules,allowMileageAndFixed:true}).total,640);});
test('per-day operator allowance remains separate',()=>assert.equal(calculateTransport(500,5,'Per-day amount',rules).amount,2500));
test('special duty allowance does not change daily rate or EPF basis',()=>{const employee={pay_basis:'Daily rate',daily_rate:2500,days_present:1,overtime_pay:0,unpaid_days:0,salary_advance:0,epf_eligible:true};const result=calculatePayslip(employee,{epf_employee_rate:8,epf_employer_rate:12,etf_employer_rate:3},[{kind:'Allowance',amount:500}]);assert.equal(result.basic,2500);assert.equal(result.allowanceTotal,500);assert.equal(result.epfEmployeeDeduction,200);assert.equal(employee.daily_rate,2500);});
