import 'dotenv/config';
import crypto from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import express from 'express';
import helmet from 'helmet';
import { z } from 'zod';
import { audit, initializeDatabase, pool, query, transaction, verifyPassword } from './db.js';

const app=express(); const workspaceRoot=path.dirname(path.dirname(path.dirname(fileURLToPath(import.meta.url)))); const frontendDist=path.join(workspaceRoot,'frontend','dist'); const port=Number(process.env.PORT||4173);
const roles={manage:['Owner / Director','Administrator'],projects:['Owner / Director','Administrator','Project Manager'],site:['Owner / Director','Administrator','Project Manager','Site Supervisor'],stock:['Owner / Director','Administrator','Project Manager','Site Supervisor','Storekeeper'],finance:['Owner / Director','Administrator','Finance / Accounts']};
app.use(helmet({contentSecurityPolicy:false})); app.use(express.json({limit:'2mb'}));
const wrap=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
const tokenHash=token=>crypto.createHash('sha256').update(token).digest('hex');
async function issueSession(userId){const token=crypto.randomBytes(32).toString('base64url');const expires=new Date(Date.now()+12*3600000);await query('INSERT INTO sessions (user_id,token_hash,expires_at) VALUES (?,?,?)',[userId,tokenHash(token),expires]);return{token,expires}}
const auth=wrap(async(req,res,next)=>{const token=req.headers.authorization?.replace(/^Bearer\s+/i,'');if(!token)return res.status(401).json({error:'Authentication required'});const rows=await query(`SELECT u.id,u.name,u.email,u.role,s.expires_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>UTC_TIMESTAMP() AND u.active=1`,[tokenHash(token)]);if(!rows[0])return res.status(401).json({error:'Session expired'});req.user=rows[0];next()});
const permit=allowed=>(req,res,next)=>allowed.includes(req.user.role)?next():res.status(403).json({error:'You do not have permission for this action'});
const validate=schema=>(req,res,next)=>{const result=schema.safeParse(req.body);if(!result.success)return res.status(400).json({error:'Invalid data',issues:result.error.flatten()});req.body=result.data;next()};
const getOne=async(sql,params)=>{const rows=await query(sql,params);return rows[0]};

app.get('/api/health',wrap(async(_req,res)=>{await query('SELECT 1');res.json({ok:true,database:'mysql',time:new Date().toISOString()})}));
app.post('/api/auth/login',validate(z.object({email:z.string().email(),password:z.string().min(8)})),wrap(async(req,res)=>{const user=await getOne('SELECT * FROM users WHERE email=? AND active=1',[req.body.email.toLowerCase()]);if(!user||!verifyPassword(req.body.password,user.password_hash))return res.status(401).json({error:'Incorrect email or password'});const session=await issueSession(user.id);await audit(pool,user.id,'LOGIN','session','',null,{expires:session.expires},req.ip);res.json({token:session.token,user:{id:user.id,name:user.name,email:user.email,role:user.role}})}));
app.post('/api/auth/logout',auth,wrap(async(req,res)=>{await query('DELETE FROM sessions WHERE token_hash=?',[tokenHash(req.headers.authorization.replace(/^Bearer\s+/i,''))]);res.status(204).end()}));
app.get('/api/auth/me',auth,(req,res)=>res.json({user:req.user}));

app.get('/api/bootstrap',auth,wrap(async(req,res)=>{const [projects,tasks,attendance,materials,fleet,reports]=await Promise.all([
  query('SELECT * FROM projects WHERE active=1 ORDER BY id'),query('SELECT t.*,p.name project FROM tasks t JOIN projects p ON p.id=t.project_id ORDER BY t.id'),
  query('SELECT a.id,a.employee_name name,a.role,p.name site,a.check_in `in`,a.check_out `out`,a.state FROM attendance a JOIN projects p ON p.id=a.project_id ORDER BY a.id'),
  query('SELECT * FROM materials WHERE active=1 ORDER BY id'),query('SELECT id,vehicle,registration reg,driver,status,renewal_type renewal,due_date FROM fleet ORDER BY id'),
  query("SELECT r.id,p.name site,r.supervisor,DATE_FORMAT(r.report_date,'%d %b %Y') date,r.workforce,r.work_completed work,r.issue,r.weather FROM daily_reports r JOIN projects p ON p.id=r.project_id ORDER BY r.report_date DESC,r.id DESC")]);
  const today=Date.now(); const mappedMaterials=materials.map(m=>({...m,state:m.stock<m.minimum?(m.stock<m.minimum*.5?'Critical':'Low stock'):'Available'}));const mappedFleet=fleet.map(v=>{const days=Math.ceil((new Date(v.due_date)-today)/86400000);return{...v,due:days<0?`Overdue ${Math.abs(days)} days`:`${days} days`}});res.json({user:req.user,data:{projects,tasks,attendance,materials:mappedMaterials,fleet:mappedFleet,reports}})}));

const projectSchema=z.object({name:z.string().min(3).max(180),client:z.string().min(2).max(180),manager:z.string().min(2).max(120),site:z.string().min(2).max(180),stage:z.string().min(2).max(150),budget:z.number().nonnegative(),progress:z.number().int().min(0).max(100).default(0),health:z.enum(['On track','Watch','At risk']).default('On track')});
app.post('/api/projects',auth,permit(roles.projects),validate(projectSchema),wrap(async(req,res)=>{const b=req.body;const result=await query('INSERT INTO projects (name,client,manager,site,stage,budget,progress,health) VALUES (?,?,?,?,?,?,?,?)',[b.name,b.client,b.manager,b.site,b.stage,b.budget,b.progress,b.health]);const row=await getOne('SELECT * FROM projects WHERE id=?',[result.insertId]);await audit(pool,req.user.id,'CREATE','project',row.id,null,row,req.ip);res.status(201).json(row)}));
app.patch('/api/projects/:id',auth,permit(roles.projects),validate(projectSchema.partial()),wrap(async(req,res)=>{const before=await getOne('SELECT * FROM projects WHERE id=?',[req.params.id]);if(!before)return res.status(404).json({error:'Project not found'});const fields=Object.keys(req.body);if(!fields.length)return res.json(before);await query(`UPDATE projects SET ${fields.map(k=>`${k}=?`).join(',')} WHERE id=?`,[...fields.map(k=>req.body[k]),req.params.id]);const after=await getOne('SELECT * FROM projects WHERE id=?',[req.params.id]);await audit(pool,req.user.id,'UPDATE','project',after.id,before,after,req.ip);res.json(after)}));
const taskSchema=z.object({title:z.string().min(3).max(220),projectId:z.number().int().positive(),assignee:z.string().min(2).max(120),due:z.string().min(2).max(100),priority:z.enum(['Low','Medium','High']),status:z.enum(['Not started','In progress','Blocked','Completed','Approved']).default('Not started'),notes:z.string().max(3000).default('')});
app.post('/api/tasks',auth,permit(roles.site),validate(taskSchema),wrap(async(req,res)=>{const b=req.body;const result=await query('INSERT INTO tasks (title,project_id,assignee,due,priority,status,notes) VALUES (?,?,?,?,?,?,?)',[b.title,b.projectId,b.assignee,b.due,b.priority,b.status,b.notes]);const row=await getOne('SELECT t.*,p.name project FROM tasks t JOIN projects p ON p.id=t.project_id WHERE t.id=?',[result.insertId]);await audit(pool,req.user.id,'CREATE','task',row.id,null,row,req.ip);res.status(201).json(row)}));
app.patch('/api/tasks/:id',auth,permit(roles.site),validate(z.object({status:z.enum(['Not started','In progress','Blocked','Completed','Approved'])})),wrap(async(req,res)=>{const before=await getOne('SELECT * FROM tasks WHERE id=?',[req.params.id]);if(!before)return res.status(404).json({error:'Task not found'});await query('UPDATE tasks SET status=?,approved_by=? WHERE id=?',[req.body.status,req.body.status==='Approved'?req.user.id:null,req.params.id]);const after=await getOne('SELECT * FROM tasks WHERE id=?',[req.params.id]);await audit(pool,req.user.id,'UPDATE','task',after.id,before,after,req.ip);res.json(after)}));
const attendanceSchema=z.object({name:z.string().min(2).max(120),role:z.string().min(2).max(100),projectId:z.number().int().positive(),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),state:z.enum(['On site','Late','Checked out','Absent']).default('On site')});
app.post('/api/attendance',auth,permit(roles.site),validate(attendanceSchema),wrap(async(req,res)=>{try{const b=req.body;const now=b.state==='Absent'?null:new Date().toISOString().slice(11,19);const result=await query('INSERT INTO attendance (employee_name,role,project_id,work_date,check_in,state,confirmed_by) VALUES (?,?,?,?,?,?,?)',[b.name,b.role,b.projectId,b.date,now,b.state,req.user.id]);const row=await getOne('SELECT * FROM attendance WHERE id=?',[result.insertId]);await audit(pool,req.user.id,'CREATE','attendance',row.id,null,row,req.ip);res.status(201).json(row)}catch(e){if(e.code==='ER_DUP_ENTRY')return res.status(409).json({error:'Attendance already exists for this employee and date'});throw e}}));
app.post('/api/attendance/:id/toggle',auth,permit(roles.site),wrap(async(req,res)=>{const before=await getOne('SELECT * FROM attendance WHERE id=?',[req.params.id]);if(!before)return res.status(404).json({error:'Attendance record not found'});const now=new Date().toISOString().slice(11,19);if(before.check_in&&!before.check_out)await query("UPDATE attendance SET check_out=?,state='Checked out',confirmed_by=? WHERE id=?",[now,req.user.id,before.id]);else await query("UPDATE attendance SET check_in=?,check_out=NULL,state='On site',confirmed_by=? WHERE id=?",[now,req.user.id,before.id]);const after=await getOne('SELECT * FROM attendance WHERE id=?',[before.id]);await audit(pool,req.user.id,'UPDATE','attendance',after.id,before,after,req.ip);res.json(after)}));
const materialSchema=z.object({name:z.string().min(2).max(180),unit:z.string().min(1).max(30),stock:z.number().nonnegative(),minimum:z.number().nonnegative(),site:z.string().min(2).max(180),supplier:z.string().max(180).optional()});
app.post('/api/materials',auth,permit(roles.stock),validate(materialSchema),wrap(async(req,res)=>{const b=req.body;const result=await query('INSERT INTO materials (name,unit,stock,minimum,site,supplier) VALUES (?,?,?,?,?,?)',[b.name,b.unit,b.stock,b.minimum,b.site,b.supplier||null]);const row=await getOne('SELECT * FROM materials WHERE id=?',[result.insertId]);await audit(pool,req.user.id,'CREATE','material',row.id,null,row,req.ip);res.status(201).json(row)}));
app.post('/api/materials/:id/movements',auth,permit(roles.stock),validate(z.object({type:z.enum(['Receipt','Issue','Return','Adjustment']),quantity:z.number().positive().max(1000000),reference:z.string().max(120).optional(),notes:z.string().max(500).optional()})),wrap(async(req,res)=>{try{const after=await transaction(async connection=>{const [rows]=await connection.execute('SELECT * FROM materials WHERE id=? FOR UPDATE',[req.params.id]);const before=rows[0];if(!before)throw Object.assign(new Error('Material not found'),{status:404});const direction=['Receipt','Return'].includes(req.body.type)?1:-1;const stock=Number(before.stock)+direction*req.body.quantity;if(stock<0)throw Object.assign(new Error('Insufficient stock'),{status:409});await connection.execute('UPDATE materials SET stock=? WHERE id=?',[stock,before.id]);await connection.execute('INSERT INTO stock_movements (material_id,movement_type,quantity,reference,notes,user_id) VALUES (?,?,?,?,?,?)',[before.id,req.body.type,req.body.quantity,req.body.reference||'',req.body.notes||'',req.user.id]);const updated={...before,stock};await audit(connection,req.user.id,'STOCK_MOVEMENT','material',before.id,before,updated,req.ip);return updated});res.status(201).json(after)}catch(e){if(e.status)return res.status(e.status).json({error:e.message});throw e}}));
const fleetSchema=z.object({vehicle:z.string().min(2).max(180),registration:z.string().min(2).max(60),driver:z.string().max(120).optional(),status:z.enum(['Available','Assigned','Repair','Inactive']),renewal:z.string().min(2).max(100),dueDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/)});
app.post('/api/fleet',auth,permit(roles.projects),validate(fleetSchema),wrap(async(req,res)=>{const b=req.body;const result=await query('INSERT INTO fleet (vehicle,registration,driver,status,renewal_type,due_date) VALUES (?,?,?,?,?,?)',[b.vehicle,b.registration,b.driver||null,b.status,b.renewal,b.dueDate]);const row=await getOne('SELECT * FROM fleet WHERE id=?',[result.insertId]);await audit(pool,req.user.id,'CREATE','fleet',row.id,null,row,req.ip);res.status(201).json(row)}));
app.patch('/api/fleet/:id',auth,permit(roles.projects),validate(fleetSchema.partial()),wrap(async(req,res)=>{const before=await getOne('SELECT * FROM fleet WHERE id=?',[req.params.id]);if(!before)return res.status(404).json({error:'Asset not found'});const map={renewal:'renewal_type',dueDate:'due_date'};const fields=Object.keys(req.body);if(fields.length)await query(`UPDATE fleet SET ${fields.map(k=>`${map[k]||k}=?`).join(',')} WHERE id=?`,[...fields.map(k=>req.body[k]),req.params.id]);const after=await getOne('SELECT * FROM fleet WHERE id=?',[req.params.id]);await audit(pool,req.user.id,'UPDATE','fleet',after.id,before,after,req.ip);res.json(after)}));
app.post('/api/reports',auth,permit(roles.site),validate(z.object({projectId:z.number().int().positive(),workforce:z.number().int().min(0).max(10000),work:z.string().min(3).max(5000),issue:z.string().max(3000).optional(),weather:z.string().max(100).optional()})),wrap(async(req,res)=>{try{const b=req.body;const date=new Date().toISOString().slice(0,10);const result=await query('INSERT INTO daily_reports (project_id,supervisor,report_date,workforce,work_completed,issue,weather,created_by) VALUES (?,?,?,?,?,?,?,?)',[b.projectId,req.user.name,date,b.workforce,b.work,b.issue||'',b.weather||'',req.user.id]);const row=await getOne('SELECT * FROM daily_reports WHERE id=?',[result.insertId]);await audit(pool,req.user.id,'CREATE','daily_report',row.id,null,row,req.ip);res.status(201).json(row)}catch(e){if(e.code==='ER_DUP_ENTRY')return res.status(409).json({error:'A report for this project already exists today'});throw e}}));
app.get('/api/users',auth,permit(roles.manage),wrap(async(_req,res)=>res.json(await query('SELECT id,name,email,role,active,created_at FROM users ORDER BY name'))));
app.post('/api/users',auth,permit(roles.manage),validate(z.object({name:z.string().min(2).max(120),email:z.string().email(),password:z.string().min(10),role:z.enum(['Owner / Director','Administrator','Project Manager','Site Supervisor','Storekeeper','Finance / Accounts','Employee','Read-Only Viewer'])})),wrap(async(req,res)=>{const {hashPassword}=await import('./db.js');const b=req.body;const result=await query('INSERT INTO users (name,email,password_hash,role) VALUES (?,?,?,?)',[b.name,b.email.toLowerCase(),hashPassword(b.password),b.role]);res.status(201).json(await getOne('SELECT id,name,email,role,active FROM users WHERE id=?',[result.insertId]))}));
app.get('/api/audit',auth,permit(roles.manage),wrap(async(_req,res)=>res.json(await query('SELECT a.id,u.name user,a.action,a.entity,a.entity_id entityId,a.created_at createdAt FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.id DESC LIMIT 500'))));
app.get('/api/notifications',auth,wrap(async(req,res)=>res.json(await query('SELECT * FROM notifications WHERE user_id IS NULL OR user_id=? ORDER BY id DESC LIMIT 100',[req.user.id]))));
app.use('/api',(req,res)=>res.status(404).json({error:'API endpoint not found'})); app.use(express.static(frontendDist)); app.get('*',(_req,res)=>res.sendFile(path.join(frontendDist,'index.html')));
app.use((err,_req,res,_next)=>{console.error(err);if(err.code==='ER_DUP_ENTRY')return res.status(409).json({error:'This record already exists'});res.status(500).json({error:'Unexpected server error'})});

await initializeDatabase();
app.listen(port,()=>console.log(`GKUC SiteOps running with MySQL at http://127.0.0.1:${port}`));
