import React,{useEffect,useState} from 'react';
import {api,post,patch} from '../api.js';
import {Table,Row,Badge,FormModal,Field,TextArea,SelectField} from '../ui.jsx';
import Attachments from '../Attachments.jsx';

export default function Hiring({companies,companyId,reload}){
  const [rows,setRows]=useState([]),[candidate,setCandidate]=useState(null),[form,setForm]=useState(null),[roles,setRoles]=useState([]),[access,setAccess]=useState(false),[error,setError]=useState('');
  const [positionFilter,setPositionFilter]=useState(''),[compareIds,setCompareIds]=useState([]);
  const score=row=>{const value=typeof row.screening_scores==='string'?JSON.parse(row.screening_scores):row.screening_scores;return value||null;};
  const applicants=rows.filter(row=>['Applicant','Screening','Shortlisted','Dropped'].includes(row.status)&&(!positionFilter||row.position===positionFilter));
  const compared=rows.filter(row=>compareIds.includes(row.id));
  const load=()=>api('/hiring').then(setRows).catch(e=>setError(e.message));
  const open=async id=>{try{setCandidate(await api(`/hiring/${id}`));setError('');}catch(e){setError(e.message);}};
  useEffect(()=>{load();api('/hiring/roles').then(setRoles).catch(()=>setRoles([]));},[]);
  const refresh=async()=>{await load();if(candidate)await open(candidate.id);};
  return <>
    <div className="panel-title"><h2>Hiring pipeline</h2><div className="row-actions"><button className="secondary" onClick={()=>setForm({type:'candidate'})}>Add previously shortlisted</button><button className="primary" onClick={()=>setForm({type:'applicant'})}>Add applicant / CV</button></div></div>
    <p className="form-note">Applicant pool → CV screening and score → Shortlist → Interview → Select or drop → Employee. Job advertising still happens outside the system.</p>
    {error&&<p className="form-error" role="alert">{error}</p>}
    <div className="attendance-summary">{['Applicant','Screening','Shortlisted','Interviewing','Selected','Dropped','Hired'].map(status=><div className="summary" key={status}><div><strong>{rows.filter(r=>r.status===status).length}</strong><span>{status}</span></div></div>)}</div>
    <section className="panel hiring-pool"><div className="panel-title"><h2>Applicant CV review</h2><label>Position <select value={positionFilter} onChange={e=>setPositionFilter(e.target.value)}><option value="">All positions</option>{[...new Set(rows.map(r=>r.position).filter(Boolean))].sort().map(value=><option key={value}>{value}</option>)}</select></label></div>
      <p className="form-note">Open an applicant to upload or read their CV, then score experience, qualifications and role fit from 0–5. Select up to four applicants to compare.</p>
      <Table columns={['Compare','Applicant','Position','Screening score','Stage','Action']} template="70px minmax(150px,1.2fr) minmax(130px,1fr) 125px 115px 85px" empty="No applicants for this position yet.">
        {applicants.map(row=><Row key={row.id} template="70px minmax(150px,1.2fr) minmax(130px,1fr) 125px 115px 85px"><input type="checkbox" aria-label={`Compare ${row.name}`} checked={compareIds.includes(row.id)} onChange={e=>setCompareIds(ids=>e.target.checked?[...ids,row.id].slice(-4):ids.filter(id=>id!==row.id))}/><strong>{row.name}</strong><span>{row.position||'Not specified'}</span><strong>{score(row)?`${score(row).total} / 15`:'Not scored'}</strong><Badge>{row.status}</Badge><button className="secondary" onClick={()=>open(row.id)}>Review</button></Row>)}
      </Table>
      {compared.length>0&&<div className="hiring-comparison">{compared.map(row=><article key={row.id}><h3>{row.name}</h3><p>{row.position||'Position not specified'} · {row.status}</p><strong>{score(row)?`${score(row).total} / 15`:'Not scored'}</strong><span>Experience {score(row)?.experience??'—'} · Qualifications {score(row)?.qualifications??'—'} · Role fit {score(row)?.roleFit??'—'}</span><button className="secondary" onClick={()=>open(row.id)}>Open CV & review</button></article>)}</div>}
    </section>
    <Table title="Candidates" columns={['Candidate','Position','Contact','Status','']} template="minmax(160px,1fr) 160px minmax(150px,1fr) 110px 80px" empty="Add candidates after HR has shortlisted them.">
      {rows.map(row=><Row key={row.id} template="minmax(160px,1fr) 160px minmax(150px,1fr) 110px 80px"><strong>{row.name}</strong><span>{row.position||'—'}</span><span>{row.phone}<small>{row.email}</small></span><Badge>{row.status}</Badge><button className="secondary" onClick={()=>open(row.id)}>Open</button></Row>)}
    </Table>
    {candidate&&<section className="panel">
      <div className="panel-title"><h2>{candidate.name}</h2><button className="secondary" onClick={()=>setCandidate(null)}>Close profile</button></div>
      <div className="report-form"><p>{candidate.phone}<br/>{candidate.email}<br/>{candidate.address}</p><div><Badge>{candidate.status}</Badge><p>{candidate.decision_notes}</p></div>
      {candidate.status!=='Hired'&&<div className="wide row-actions"><button className="secondary" onClick={()=>setForm({type:'candidate',...candidate})}>Edit details</button>{['Applicant','Screening','Shortlisted','Dropped'].includes(candidate.status)&&<button className="secondary" onClick={()=>setForm({type:'screening'})}>Screen CV / shortlist</button>}{!['Applicant','Screening'].includes(candidate.status)&&<button className="secondary" onClick={()=>setForm({type:'decision'})}>Record selection decision</button>}{['Shortlisted','Interviewing'].includes(candidate.status)&&<button className="secondary" onClick={()=>setForm({type:'interview'})}>Schedule interview</button>}{candidate.status==='Selected'&&<button className="primary" onClick={()=>{setAccess(false);setForm({type:'hire'});}}>Convert to employee</button>}</div>}
      {candidate.screening_scores&&<p className="form-note wide">CV screening: {score(candidate)?.total} / 15 · {candidate.screening_notes}</p>}
      {candidate.status==='Hired'&&<p className="form-note wide">Employee profile #{candidate.employee_id} created. CV files are now available on that employee profile. HR can complete their pay settings in People.</p>}</div>
      {candidate.status!=='Hired'&&<Attachments ownerType="candidate" ownerId={candidate.id} title="CV & candidate documents" canUpload canDelete={false} />}
      <Table title="Interview history" columns={['Date / time','Interviewer','Location','Status','Notes','']} template="170px 140px 140px 100px minmax(180px,1fr) 70px" empty="No interviews recorded.">{candidate.interviews.map(i=><Row key={i.id} template="170px 140px 140px 100px minmax(180px,1fr) 70px"><span>{String(i.scheduled_at).replace('T',' ').slice(0,16)}</span><span>{i.interviewer}</span><span>{i.location}</span><Badge>{i.status}</Badge><span>{i.notes}</span>{candidate.status!=='Hired'&&<button className="secondary" onClick={()=>setForm({type:'interview',...i})}>Edit</button>}</Row>)}</Table>
    </section>}
    {['candidate','applicant'].includes(form?.type)&&<FormModal title={form.id?'Edit candidate':form.type==='applicant'?'Add applicant':'Add previously shortlisted candidate'} close={()=>setForm(null)} label="Save" onSubmit={async v=>{const result=form.id?await patch(`/hiring/${form.id}`,v):await post(form.type==='applicant'?'/hiring/applicants':'/hiring',v);await load();await open(result.id);}}><Field name="name" label="Name" defaultValue={form.name}/><Field name="phone" label="Phone" type="tel" required={false} defaultValue={form.phone}/><Field name="email" label="Email" type="email" required={false} defaultValue={form.email}/><Field name="position" label="Position applied for" required={false} defaultValue={form.position}/><TextArea name="address" label="Address" required={false} defaultValue={form.address}/><p className="form-note wide">After saving, upload the CV in this applicant's profile. HR reviews and scores it before shortlisting.</p></FormModal>}
    {form?.type==='screening'&&<FormModal title={`CV screening · ${candidate.name}`} close={()=>setForm(null)} label="Save screening" onSubmit={async v=>{await patch(`/hiring/${candidate.id}/screening`,{experience:Number(v.experience),qualifications:Number(v.qualifications),roleFit:Number(v.roleFit),notes:v.notes,decision:v.decision});await refresh();}}><Field name="experience" label="Relevant experience (0–5)" type="number" min="0" max="5" defaultValue={score(candidate)?.experience??0}/><Field name="qualifications" label="Qualifications (0–5)" type="number" min="0" max="5" defaultValue={score(candidate)?.qualifications??0}/><Field name="roleFit" label="Role fit (0–5)" type="number" min="0" max="5" defaultValue={score(candidate)?.roleFit??0}/><SelectField name="decision" label="Screening decision" options={['Screening','Shortlisted','Dropped']} defaultValue={candidate.status==='Applicant'?'Screening':candidate.status}/><TextArea name="notes" label="CV evidence and review notes" defaultValue={candidate.screening_notes||''}/><p className="form-note wide">Read the uploaded CV before scoring. A shortlist decision enables interview scheduling.</p></FormModal>}
    {form?.type==='decision'&&<FormModal title="Record hiring decision" close={()=>setForm(null)} label="Save decision" onSubmit={async v=>{await patch(`/hiring/${candidate.id}`,v);await refresh();}}><SelectField name="status" label="Decision" options={['Shortlisted','Interviewing','Selected','Dropped']} defaultValue={candidate.status}/><TextArea name="decisionNotes" label="Decision notes" required={false} defaultValue={candidate.decision_notes}/></FormModal>}
    {form?.type==='interview'&&<FormModal title={form.id?'Update interview':'Schedule interview'} close={()=>setForm(null)} label="Save interview" onSubmit={async v=>{if(form.id)await patch(`/hiring/${candidate.id}/interviews/${form.id}`,v);else await post(`/hiring/${candidate.id}/interviews`,v);await refresh();}}><Field name="scheduledAt" label="Interview date and time (Sri Lanka)" type="datetime-local" defaultValue={form.scheduled_at?.slice(0,16)}/><Field name="interviewer" label="Interviewer" defaultValue={form.interviewer}/><Field name="location" label="Location / meeting link" required={false} defaultValue={form.location}/><SelectField name="status" label="Interview status" options={['Scheduled','Completed','Cancelled','No show']} defaultValue={form.status||'Scheduled'}/><TextArea name="notes" label="Interview notes and outcome" required={false} defaultValue={form.notes}/></FormModal>}
    {form?.type==='hire'&&<FormModal title={`Hire ${candidate.name}`} close={()=>setForm(null)} label="Create employee" onSubmit={async v=>{await post(`/hiring/${candidate.id}/hire`,{code:v.code,startDate:v.startDate,workerType:v.workerType,companyId:Number(v.companyId),createAccess:access,...(access?{roleId:Number(v.roleId),password:v.password}:{})});await refresh();await reload();}}><Field name="code" label="Employee ID"/><Field name="startDate" label="Actual employment start date" type="date"/><SelectField name="workerType" label="Employee type" options={['Office','Site']}/><SelectField name="companyId" label="Payroll company" options={companies.map(c=>[c.id,c.name])} defaultValue={companyId}/><label className="wide"><input type="checkbox" checked={access} onChange={e=>setAccess(e.target.checked)}/>Also create system access</label>{access&&<><p className="form-note wide">A candidate email is required. You can assign only roles within your own authority. The MD can assign additional access later.</p><SelectField name="roleId" label="Access role" options={roles.map(r=>[r.id,r.name])}/><Field name="password" label="Temporary password (12+ characters)" type="password"/></>}<p className="form-note wide">Creates one employee profile and preserves the CV there. Pay rates start at zero and EPF/ETF eligibility remains off until HR configures them.</p></FormModal>}
  </>;
}
