import React, { useEffect, useState } from 'react';
import { api, post, rupees, shortDate, slug, todayInput } from '../api.js';
import { Badge, Field, FormModal, Page, Row, SelectField, Table, Tabs, TextArea, useLiveList } from '../ui.jsx';

const TABS=['Locations','Tool handovers','BOQ usage'];
const count=rows=>rows.reduce((sum,row)=>sum+Number(row.outstanding||0),0);
const quantityFlag=row=>row.overrun?'BOQ exceeded':row.quoteOverrun?'Quote exceeded':row.forecastOverrun?'BOQ at risk':row.quoteForecastOverrun?'Quote at risk':row.unplanned?'No plan link':'Within plan';
const needsReview=row=>row.forecastOverrun||row.quoteForecastOverrun||row.unplanned;

export default function Inventory({data,can}){
  const [tab,setTab]=useState(TABS[0]),[inventory,setInventory]=useState(null),[issuing,setIssuing]=useState(false),[returning,setReturning]=useState(null),[consuming,setConsuming]=useState(false),[counting,setCounting]=useState(false);
  const load=()=>api('/materials/inventory').then(setInventory).catch(()=>setInventory(null));
  useLiveList(load);useEffect(()=>{load();},[]);
  if(!inventory)return <Page title="Stock locations" subtitle="Loading the live store and site register…"><p className="empty-state">Loading inventory…</p></Page>;
  const available=inventory.materials.reduce((sum,m)=>sum+Number(m.stock)*Number(m.unitCost||0),0);
  const openLoans=inventory.loans.filter(l=>Number(l.outstanding)>0);
  const warnings=inventory.siteIssues.filter(needsReview);
  return <Page title="Stock locations" subtitle="See what remains in the storeroom, what has gone to each site, and who is holding returnable tools.">
    <div className="inventory-top"><div><span>Store stock value</span><strong>{rupees(available)}</strong><small>Consumables and returnable tools</small></div><div><span>Tools at sites</span><strong>{count(openLoans)}</strong><small>{openLoans.length} open handovers</small></div><div><span>Material plan flags</span><strong>{warnings.length}</strong><small>BOQ or accepted quote quantity needs review</small></div></div>
    <Tabs tabs={TABS} active={tab} onChange={setTab}/>
    {tab==='Locations'&&<><div className="toolbar"><span className="segment-label">Uncounted legacy site balances are estimates until physically checked.</span>{(can.stock||can.reports)&&<span className="row-actions"><button className="secondary" onClick={()=>setCounting(true)}>Count site stock</button><button className="secondary" onClick={()=>setConsuming(true)}>Record material used</button></span>}</div><Locations inventory={inventory}/></>}
    {tab==='Tool handovers'&&<><div className="toolbar"><span className="segment-label">The person handing over and taking each tool is recorded.</span>{can.stock&&<button className="secondary" onClick={()=>setIssuing(true)}>Hand over tool</button>}</div><Table title="Open and returned tool loans" columns={['Tool','Current location','Outstanding','Taken by','Handed over by','Issued','']} template="minmax(180px,1.2fr) minmax(170px,1fr) 110px 150px 150px 125px 105px" empty="No tools have been handed over.">{inventory.loans.map(l=><Row template="minmax(180px,1.2fr) minmax(170px,1fr) 110px 150px 150px 125px 105px" key={l.id}><div><strong>{l.material}</strong><small>{l.reference||`Loan #${l.id}`}</small></div><span>{Number(l.outstanding)>0?l.project:'Returned to store'}</span><strong>{l.outstanding} {l.unit}</strong><span>{l.takenBy}</span><span>{l.handedOverBy}</span><span>{shortDate(l.issuedAt)}</span>{can.stock&&Number(l.outstanding)>0?<button className="status-button" onClick={()=>setReturning(l)}>Return</button>:<Badge tone="on-track">Returned</Badge>}</Row>)}</Table></>}
    {tab==='BOQ usage'&&<BoqUsage rows={inventory.siteIssues}/>}
    {issuing&&<IssueForm materials={inventory.materials.filter(m=>m.stockKind==='Returnable')} projects={data.projects} close={()=>setIssuing(false)} reload={load}/>}
    {returning&&<ReturnForm loan={returning} close={()=>setReturning(null)} reload={load}/>}
    {consuming&&<ConsumptionForm materials={inventory.materials.filter(m=>m.stockKind==='Consumable')} projects={data.projects} close={()=>setConsuming(false)} reload={load}/>}
    {counting&&<SiteCountForm materials={inventory.materials.filter(m=>m.stockKind==='Consumable')} projects={data.projects} close={()=>setCounting(false)} reload={load}/>}
  </Page>;
}

function Locations({inventory}){
  const t='minmax(180px,1.3fr) 120px minmax(150px,1fr) 120px 130px 130px';
  const positions=[...inventory.materials.map(m=>({id:`store-${m.id}`,item:m.name,kind:m.stockKind,location:m.site||'Storeroom',quantity:Number(m.stock),unit:m.unit,value:Number(m.stock)*Number(m.unitCost||0)})),
    ...inventory.siteIssues.filter(r=>Number(r.siteBalance)>0).map(r=>({id:`site-${r.projectId}-${r.materialId}`,item:r.material,kind:'Consumable',location:r.project,quantity:r.siteBalance,unit:r.unit,value:null,verified:r.balanceVerified})),
    ...inventory.loans.filter(r=>Number(r.outstanding)>0).map(r=>({id:`loan-${r.id}`,item:r.material,kind:'Returnable',location:r.project,quantity:r.outstanding,unit:r.unit,value:null,holder:r.takenBy}))];
  const byLocation=[...positions.reduce((map,row)=>{const item=map.get(row.location)||{name:row.location,lines:0,quantity:0};item.lines++;item.quantity+=Number(row.quantity);map.set(row.location,item);return map;},new Map()).values()];
  const max=Math.max(1,...byLocation.map(r=>r.lines));
  return <><section className="workspace-surface"><div className="workspace-section-heading"><div><span className="section-kicker">Live distribution</span><h2>Store and site positions</h2></div></div><div className="cost-bars">{byLocation.map(r=><div key={r.name}><span>{r.name}</span><i><b style={{width:`${r.lines/max*100}%`}}/></i><strong>{r.lines} lines</strong></div>)}</div></section><div style={{height:14}}/><Table title="Storeroom and site positions" columns={['Item','Kind','Location','Quantity','Value in store','Custodian / count']} template={t} empty="No stock positions.">{positions.map(r=><Row template={t} key={r.id}><strong>{r.item}</strong><Badge tone={slug(r.kind)}>{r.kind}</Badge><span>{r.location}</span><strong>{r.quantity} {r.unit}</strong><span>{r.value===null?'—':rupees(r.value)}</span><span>{r.holder|| (r.verified===false?'Count needed':r.verified===true?'Count verified':'—')}</span></Row>)}</Table><div style={{height:14}}/><Table title="Vehicles and equipment locations" columns={['Asset','Type','Location','Status']} template="minmax(200px,1.4fr) 110px minmax(180px,1fr) 120px" empty="No assets recorded.">{[...inventory.vehicles.map(v=>({id:`v-${v.id}`,name:`${v.vehicle} · ${v.registration}`,type:'Vehicle',location:v.project||(v.status==='Assigned'?'Assignment not linked to site':'Depot / office'),status:v.status})),...inventory.equipment.map(e=>({id:`e-${e.id}`,name:`${e.name} · ${e.code}`,type:'Equipment',location:e.project||(e.status==='Assigned'?'Assignment not linked to site':'Store'),status:e.status}))].map(a=><Row template="minmax(200px,1.4fr) 110px minmax(180px,1fr) 120px" key={a.id}><strong>{a.name}</strong><span>{a.type}</span><span>{a.location}</span><Badge tone={slug(a.status)}>{a.status}</Badge></Row>)}</Table></>;
}

function BoqUsage({rows}){
  const template='minmax(220px,1.6fr) 110px 110px 120px 140px 130px 130px 150px';
  return <><section className="workspace-surface"><div className="workspace-section-heading"><div><span className="section-kicker">Quantity control</span><h2>Issued + requested against BOQ and quote</h2></div></div>
    <div className="cost-bars">{rows.filter(r=>r.allowedQuantity!==null||r.quotedQuantity!==null).slice(0,12).map(r=>{const limit=Math.min(...[r.allowedQuantity,r.quotedQuantity].filter(v=>v!==null).map(Number));return <div key={`${r.projectId}-${r.materialId}`}><span>{r.material} · {r.project}</span><i><b style={{width:`${Math.min(100,limit?Number(r.forecastQuantity)/limit*100:100)}%`,background:needsReview(r)?'#b32539':undefined}}/></i><strong>{r.forecastQuantity}/{limit} {r.unit}</strong></div>;})}</div></section>
    <div style={{height:14}}/><Table title="Material quantity exceptions" columns={['Project / material','Issued','Used on site','Still on site','Pending requests','BOQ allowed','Accepted quote','Flag']} template={template} empty="No linked material lines or site issues yet.">
      {rows.map(r=><Row template={template} key={`${r.projectId}-${r.materialId}`}><div><strong>{r.material}</strong><small>{r.project}</small></div><span>{r.quantity} {r.unit}</span><span>{r.consumedQuantity} {r.unit}</span><strong>{r.siteBalance} {r.unit}</strong><span>{r.plannedQuantity} {r.unit}</span><span>{r.allowedQuantity===null?'Not linked':`${r.allowedQuantity} ${r.unit}`}</span><span>{r.quotedQuantity===null?'Not linked':`${r.quotedQuantity} ${r.unit}`}</span><Badge tone={r.overrun||r.quoteOverrun?'at-risk':needsReview(r)?'watch':'on-track'}>{quantityFlag(r)}</Badge></Row>)}</Table></>;
}

function IssueForm({materials,projects,close,reload}){return <FormModal title="Hand over a returnable tool" close={close} label="Record handover" onSubmit={async v=>{await post('/materials/loans',{materialId:Number(v.materialId),projectId:Number(v.projectId),quantity:Number(v.quantity),takenBy:v.takenBy,handedOverBy:v.handedOverBy,conditionOut:v.conditionOut||undefined,reference:v.reference||undefined});await reload();}}><SelectField name="materialId" label="Tool" options={materials.map(m=>[m.id,`${m.name} · ${m.stock} ${m.unit} in store`])}/><SelectField name="projectId" label="Site" options={projects.map(p=>[p.id,p.name])}/><Field name="quantity" label="Quantity" type="number" min="0.001" step="0.001"/><Field name="takenBy" label="Taken by"/><Field name="handedOverBy" label="Handed over by"/><Field name="reference" label="Handover reference" required={false}/><TextArea name="conditionOut" label="Condition when issued" required={false}/></FormModal>}
function ReturnForm({loan,close,reload}){return <FormModal title={`Return ${loan.material} from ${loan.project}`} close={close} label="Record return" onSubmit={async v=>{await post(`/materials/loans/${loan.id}/returns`,{quantity:Number(v.quantity),receivedBackBy:v.receivedBackBy,conditionIn:v.conditionIn||undefined,reference:v.reference||undefined});await reload();}}><Field name="quantity" label={`Quantity (max ${loan.outstanding})`} type="number" min="0.001" max={loan.outstanding} step="0.001" defaultValue={loan.outstanding}/><Field name="receivedBackBy" label="Received back by"/><Field name="reference" label="Return reference" required={false}/><TextArea name="conditionIn" label="Condition on return" required={false}/></FormModal>}
function ConsumptionForm({materials,projects,close,reload}){return <FormModal title="Record material used on site" close={close} label="Record usage" onSubmit={async v=>{await post('/materials/site-consumption',{materialId:Number(v.materialId),projectId:Number(v.projectId),quantity:Number(v.quantity),consumedOn:v.consumedOn,notes:v.notes||undefined});await reload();}}><SelectField name="materialId" label="Material" options={materials.map(m=>[m.id,m.name])}/><SelectField name="projectId" label="Project site" options={projects.map(p=>[p.id,p.name])}/><Field name="quantity" label="Quantity used" type="number" min="0.001" step="0.001"/><Field name="consumedOn" label="Used on" type="date" defaultValue={todayInput()}/><TextArea name="notes" label="Work completed / notes" required={false}/></FormModal>}
function SiteCountForm({materials,projects,close,reload}){return <FormModal title="Confirm stock physically at a site" close={close} label="Save site count" onSubmit={async v=>{await post('/materials/site-counts',{materialId:Number(v.materialId),projectId:Number(v.projectId),countedQuantity:Number(v.countedQuantity),notes:v.notes||undefined});await reload();}}><SelectField name="materialId" label="Material" options={materials.map(m=>[m.id,m.name])}/><SelectField name="projectId" label="Project site" options={projects.map(p=>[p.id,p.name])}/><Field name="countedQuantity" label="Physically counted quantity" type="number" min="0" step="0.001"/><TextArea name="notes" label="Counter, condition or variance reason" required={false}/></FormModal>}
