import React, { useEffect, useState } from 'react';
import { api, post, rupees, todayInput } from '../api.js';
import { Field, FormModal, SelectField } from '../ui.jsx';

const money = value => rupees(Number(value || 0));

export default function ManagementAccounts({ companyId, company, projects, can }) {
  const [period, setPeriod] = useState(todayInput().slice(0, 7));
  const [pack, setPack] = useState(null);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const [action, setAction] = useState('');
  const load = async () => {
    setError('');
    try { setPack(await api(`/finance/management-accounts?companyId=${companyId}&period=${period}`)); }
    catch (failure) { setPack(null); setError(failure.message); }
  };
  useEffect(() => { setPack(null); load(); }, [companyId, period]);
  const submit = async (path, body) => {
    setBusy(true); setError('');
    try { await post(`/finance/management-accounts/${path}`, { companyId, period, ...body }); setAction(''); await load(); }
    catch (failure) { setError(failure.message); throw failure; }
    finally { setBusy(false); }
  };

  return <div className="management-pack">
    <header className="management-pack-header"><div><span>Internal management accounts · {company?.name}</span><h2>Monthly management pack</h2><p>Company-separated, management-use figures. This is not an audited income statement or balance sheet.</p></div><label>Reporting month<input type="month" value={period} onChange={event => setPeriod(event.target.value)} /></label></header>
    {error && <p className="form-error" role="alert">{error}</p>}
    {!pack ? <p className="empty-state">Preparing the monthly pack…</p> : <>
      <div className={`management-close-state ${pack.close?.status === 'Closed' ? 'closed' : ''}`}><div><strong>{pack.close?.status === 'Closed' ? `Closed · version ${pack.close.version}` : 'Open for review'}</strong><p>{pack.close?.status === 'Closed' ? `Snapshot preserved from ${String(pack.close.closedAt).slice(0, 10)}. ${pack.close.closeNote}` : 'Review the source schedules, enter any justified adjustments, then close the month.'}</p>{pack.close?.changedSinceClose && <p className="form-error">Source records changed after close. The saved pack has not changed; reopen and close a new version after review.</p>}</div>{can.finance && <div>{pack.close?.status === 'Closed' ? <button type="button" className="secondary" onClick={() => setAction('reopen')}>Reopen with reason</button> : <><button type="button" className="secondary" onClick={() => setAction('adjustment')}>Add adjustment</button><button type="button" onClick={() => setAction('close')}>Close month</button></>}</div>}</div>
      <div className="management-basis-grid"><section><small>ACCRUAL ESTIMATE</small><h3>Invoiced work basis</h3><div><span>Work invoiced before VAT</span><strong>{money(pack.accrual.billedWorkRevenue)}</strong></div><div><span>Revenue adjustments</span><strong>{money(pack.accrual.revenueAdjustments)}</strong></div><div><span>Recorded cost and billed overhead</span><strong>{money(pack.accrual.recordedCost)}</strong></div><div><span>Cost adjustments</span><strong>{money(pack.accrual.costAdjustments)}</strong></div><div className="management-total"><span>Management result</span><strong>{money(pack.accrual.result)}</strong></div></section>
        <section><small>CASH MOVEMENT CAPTURED</small><h3>Payment-record basis</h3><div><span>Receipts recorded</span><strong>{money(pack.cash.receiptsCaptured)}</strong></div><div><span>Payments captured</span><strong>{money(pack.cash.paymentsCaptured)}</strong></div><div className="management-total"><span>Captured cash movement</span><strong>{money(pack.cash.movementCaptured)}</strong></div><p>Not a reconciled bank balance. Direct bank payments may need separate recording.</p></section></div>
      <div className="management-basis-grid"><section><small>AS AT MONTH END</small><h3>Working capital</h3><div><span>Client receivables</span><strong>{money(pack.workingCapital.receivables)}</strong></div><div><span>Supplier and operating-bill payables</span><strong>{money(pack.workingCapital.payables)}</strong></div><details><summary>Client invoices still due</summary>{pack.workingCapital.receivableRows.map(row => <p key={row.id}><a href={`/finance/invoices?record=${row.id}`}>{row.reference}</a> · {money(row.outstanding)}</p>)}</details><details><summary>Supplier invoices and operating bills still due</summary>{pack.workingCapital.payableRows.map(row => <p key={row.id}>{row.reference} · {money(row.outstanding)}</p>)}{pack.workingCapital.billPayables.map(row => <p key={`bill-${row.id}`}>{row.reference} · {money(row.outstanding)}</p>)}</details></section>
        <section><small>PROJECT DELIVERY ESTIMATE</small><h3>Work in progress</h3><div><span>Estimated unbilled work</span><strong>{money(pack.wip.unbilledEstimate)}</strong></div><div><span>Management WIP adjustments</span><strong>{money(pack.wip.managementAdjustment)}</strong></div><p>Based on recorded project progress. It is shown separately and is not automatically included as earned revenue.</p></section></div>
      <section className="management-schedule"><h3>Project WIP schedule</h3><div className="report-table-scroll"><table><thead><tr>{['Project','Progress','Contract + approved changes','Billed work','Actual cost','QS forecast cost','Unbilled estimate'].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{pack.wip.projects.map(row => <tr key={row.projectId}><td><a href={`/projects/${row.projectId}`}>{row.project}</a></td><td>{row.progress}%</td><td>{money(row.contract + row.approvedVariations)}</td><td>{money(row.billed)}</td><td>{money(row.actualCost)}</td><td>{row.forecastCost ? money(row.forecastCost) : 'Not forecast'}</td><td>{money(row.unbilledEstimate)}</td></tr>)}</tbody></table></div></section>
      <section className="management-schedule"><h3>Reconciliation checks</h3><p>These checks tie the captured invoices and bills to their payments and outstanding balances as at month end. All must balance before closing. They do not replace bank reconciliation.</p><div className="report-table-scroll"><table><thead><tr><th>Control</th><th>Difference</th><th>Result</th></tr></thead><tbody>{pack.reconciliation.checks.map(row => <tr key={row.label}><td>{row.label}</td><td>{money(row.difference)}</td><td>{Math.abs(row.difference) < 0.01 ? 'Balanced' : 'Needs review'}</td></tr>)}</tbody></table></div></section>
      <section className="management-schedule"><h3>Management adjustments</h3><p>Signed amounts affect only this management pack, not invoices, cash or the underlying ledger. Use a negative adjustment to reverse a prior entry.</p><div className="report-table-scroll"><table><thead><tr>{['Category','Reference','Explanation','Project','Amount','Entered by'].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{pack.adjustments.map(row => <tr key={row.id}><td>{row.category}</td><td>{row.reference}</td><td>{row.explanation}</td><td>{projects.find(project => Number(project.id) === Number(row.projectId))?.name || 'Company'}</td><td>{money(row.amount)}</td><td>{row.createdBy}</td></tr>)}{!pack.adjustments.length && <tr><td colSpan="6">No management adjustments recorded for this month.</td></tr>}</tbody></table></div></section>
      <section className="management-schedule"><h3>Basis and limitations</h3><ul>{pack.caveats.map(item => <li key={item}>{item}</li>)}</ul></section>
    </>}
    {action === 'adjustment' && <FormModal title="Add management adjustment" label="Record adjustment" close={() => setAction('')} onSubmit={values => submit('adjustments',{category:values.category,amount:Number(values.amount),reference:values.reference,explanation:values.explanation,projectId:values.projectId?Number(values.projectId):null})}><SelectField name="category" label="Which schedule changes?" options={['Revenue','Cost','WIP','Receivable','Payable']} /><Field name="amount" label="Signed amount (LKR)" type="number" step="0.01" placeholder="Use a negative value to reduce or reverse" /><Field name="reference" label="Supporting reference" /><Field name="explanation" label="Reason and calculation" /><SelectField name="projectId" label="Project (optional)" required={false} options={[["",'Company-wide'],...projects.map(project => [project.id,project.name])]} /></FormModal>}
    {action === 'close' && <FormModal title={`Close ${period} management accounts`} label={busy?'Closing…':'Save close snapshot'} close={() => setAction('')} onSubmit={values => submit('close',{note:values.note})}><p>The current schedules and adjustments will be preserved as a versioned snapshot. This does not lock every operational module; if a source record changes later, the pack will flag it for review.</p><Field name="note" label="Review and close note" placeholder="Explain checks completed and any remaining limitations" /></FormModal>}
    {action === 'reopen' && <FormModal title={`Reopen ${period}`} label={busy?'Reopening…':'Reopen month'} close={() => setAction('')} onSubmit={values => submit('reopen',{reason:values.reason})}><p>The previous close snapshot remains in history. Enter corrections, then close a new version.</p><Field name="reason" label="Reason for reopening" /></FormModal>}
  </div>;
}
