import React, { useMemo, useState } from 'react';
import { BarChart3, Download, FileText, Search, TrendingDown, TrendingUp } from 'lucide-react';
import { rupees, shortDate, slug, todayInput } from '../api.js';

const n = value => Number(value || 0);
const pct = (value, total) => total ? Math.round(value / total * 100) : 0;
const asMoney = value => rupees(n(value));
const total = (rows, key) => rows.reduce((sum, row) => sum + n(row[key]), 0);
const countBy = (rows, key) => [...rows.reduce((map, row) => { const value = (typeof key === 'function' ? key(row) : row[key]) || 'Not recorded'; return map.set(value, (map.get(value) || 0) + 1); }, new Map())]
  .map(([label, value]) => ({ label, value }));
const table = (columns, rows) => ({ columns, rows });
const metric = (label, value, raw = value) => ({ label, value, raw: n(raw) });
const chart = rows => rows.map(row => ({ ...row, value: n(row.value), display: row.display ?? String(row.value) }));

function buildReports(project) {
  const r = project.reporting || {};
  const spend = n(project.finance.expenses); const income = n(project.finance.income); const budget = n(project.finance.budget);
  const profit = income - spend; const remaining = budget - spend;
  const completedTasks = project.tasks.filter(row => ['Completed', 'Approved'].includes(row.status)).length;
  const completedMilestones = project.milestones.filter(row => row.status === 'Completed').length;
  const outstanding = project.invoices.map(row => ({ ...row, outstanding: n(row.netPayable) - n(row.paidAmount) }));
  const overdue = outstanding.filter(row => row.outstanding > 0 && row.dueDate && String(row.dueDate).slice(0, 10) < todayInput());
  const payables = r.supplierInvoices || [];
  const payable = payables.reduce((sum, row) => sum + n(row.amount) - n(row.paidAmount), 0);
  const cash = new Map();
  for (const row of r.incomeLedger || []) { const month = String(row.date).slice(0, 7); const item = cash.get(month) || { month, inflow: 0, outflow: 0 }; item.inflow += n(row.amount); cash.set(month, item); }
  for (const row of r.expenseLedger || []) { const month = String(row.date).slice(0, 7); const item = cash.get(month) || { month, inflow: 0, outflow: 0 }; item.outflow += n(row.amount); cash.set(month, item); }
  const cashRows = [...cash.values()].sort((a, b) => a.month.localeCompare(b.month)).map(row => ({ ...row, net: row.inflow - row.outflow }));
  const taskStates = countBy(project.tasks, 'status'); const milestoneStates = countBy(project.milestones, 'status');
  const attendance = r.attendanceLedger || []; const attendancePeople = attendance.reduce((sum, row) => sum + n(row.people), 0);
  const siteReports = project.reports || []; const delayHours = total(siteReports, 'delayHours'); const issues = siteReports.filter(row => row.issue);
  const weather = countBy(siteReports, 'weather'); const materials = r.materialUsage || []; const equipment = r.equipmentUsage || [];
  const report = (id, title, category, narrative, metrics, visual, detail) => ({ id, title, category, narrative, metrics, visual: chart(visual), ...detail });
  return [
    report('executive', 'Executive project summary', 'Management', `${project.name} is ${project.progress}% complete and currently rated ${project.health.toLowerCase()}. ${completedTasks} of ${project.tasks.length} tasks and ${completedMilestones} of ${project.milestones.length} milestones are complete.`, [metric('Progress', `${project.progress}%`, project.progress), metric('Project health', project.health, project.progress), metric('Team', project.team.length), metric('Daily reports', siteReports.length)], [{ label: 'Progress', value: project.progress, display: `${project.progress}%` }, { label: 'Tasks complete', value: pct(completedTasks, project.tasks.length), display: `${completedTasks}/${project.tasks.length}` }, { label: 'Milestones', value: pct(completedMilestones, project.milestones.length), display: `${completedMilestones}/${project.milestones.length}` }], table(['Measure', 'Current position'], [['Client', project.client], ['Site', project.site], ['Manager', project.manager], ['Stage', project.stage], ['Health', project.health]])),
    report('profit-loss', 'Profit and loss', 'Commercial', `${income >= spend ? 'The project is currently profitable' : 'The project is currently recording a loss'} by ${asMoney(Math.abs(profit))}. The margin on cash received is ${pct(profit, income)}%.`, [metric('Revenue received', asMoney(income), income), metric('Recorded cost', asMoney(spend), spend), metric(profit >= 0 ? 'Profit' : 'Loss', asMoney(Math.abs(profit)), profit), metric('Margin', `${pct(profit, income)}%`, profit)], [{ label: 'Revenue', value: income, display: asMoney(income) }, { label: 'Cost', value: spend, display: asMoney(spend) }, { label: profit >= 0 ? 'Profit' : 'Loss', value: profit, display: asMoney(Math.abs(profit)) }], table(['Account', 'Amount'], [['Revenue received', asMoney(income)], ['Less: recorded project costs', asMoney(spend)], [profit >= 0 ? 'Net profit' : 'Net loss', asMoney(Math.abs(profit))]])),
    report('budget', 'Budget versus actual', 'Commercial', `${pct(spend, budget)}% of the approved budget has been used. ${remaining >= 0 ? `${asMoney(remaining)} remains available.` : `The project is over budget by ${asMoney(Math.abs(remaining))}.`}`, [metric('Approved budget', asMoney(budget), budget), metric('Actual cost', asMoney(spend), spend), metric(remaining >= 0 ? 'Remaining' : 'Overrun', asMoney(Math.abs(remaining)), remaining), metric('Utilisation', `${pct(spend, budget)}%`, spend)], [{ label: 'Budget', value: budget, display: asMoney(budget) }, { label: 'Actual', value: spend, display: asMoney(spend) }, { label: 'Balance', value: remaining, display: asMoney(Math.abs(remaining)) }], table(['Cost category', 'Actual cost', 'Share'], project.costBreakdown.map(row => [row.source, asMoney(row.total), `${pct(n(row.total), spend)}%`]))),
    report('cash-flow', 'Project cash flow', 'Finance', `Recorded cash movement is ${profit >= 0 ? 'net positive' : 'net negative'} by ${asMoney(Math.abs(profit))}. The table shows when project money entered and left the business.`, [metric('Cash in', asMoney(income), income), metric('Cash out', asMoney(spend), spend), metric('Net cash', asMoney(profit), profit), metric('Periods', cashRows.length)], cashRows.slice(-12).map(row => ({ label: row.month, value: row.net, display: asMoney(row.net) })), table(['Month', 'Cash in', 'Cash out', 'Net'], cashRows.map(row => [row.month, asMoney(row.inflow), asMoney(row.outflow), asMoney(row.net)]))),
    report('cost-category', 'Cost category analysis', 'Finance', `${project.costBreakdown[0]?.source || 'No category'} is the largest recorded cost category${project.costBreakdown[0] ? ` at ${asMoney(project.costBreakdown[0].total)}` : ''}.`, [metric('Total cost', asMoney(spend), spend), metric('Categories', project.costBreakdown.length), metric('Largest category', project.costBreakdown[0]?.source || '—'), metric('Largest share', `${pct(n(project.costBreakdown[0]?.total), spend)}%`)], project.costBreakdown.map(row => ({ label: row.source, value: row.total, display: asMoney(row.total) })), table(['Category', 'Cost', 'Share'], project.costBreakdown.map(row => [row.source, asMoney(row.total), `${pct(n(row.total), spend)}%`]))),
    report('revenue', 'Revenue and certification', 'Commercial', `${project.invoices.length} client invoice(s) have been issued with ${asMoney(total(project.invoices, 'netPayable'))} certified and ${asMoney(total(project.invoices, 'paidAmount'))} collected.`, [metric('Certified', asMoney(total(project.invoices, 'netPayable')), total(project.invoices, 'netPayable')), metric('Paid', asMoney(total(project.invoices, 'paidAmount')), total(project.invoices, 'paidAmount')), metric('Certificates', project.invoices.length), metric('Collection rate', `${pct(total(project.invoices, 'paidAmount'), total(project.invoices, 'netPayable'))}%`)], outstanding.map(row => ({ label: row.reference, value: row.netPayable, display: asMoney(row.netPayable) })), table(['Certificate', 'Type', 'Issued', 'Certified', 'Paid', 'Status'], project.invoices.map(row => [row.reference, row.kind, shortDate(row.invoiceDate), asMoney(row.netPayable), asMoney(row.paidAmount), row.status]))),
    report('receivables', 'Client receivables and ageing', 'Commercial', `${asMoney(total(outstanding, 'outstanding'))} remains due from the client. ${overdue.length} invoice(s) are past their due date.`, [metric('Outstanding', asMoney(total(outstanding, 'outstanding')), total(outstanding, 'outstanding')), metric('Overdue invoices', overdue.length), metric('Open invoices', outstanding.filter(row => row.outstanding > 0).length), metric('Paid invoices', outstanding.filter(row => row.outstanding <= 0).length)], outstanding.filter(row => row.outstanding > 0).map(row => ({ label: row.reference, value: row.outstanding, display: asMoney(row.outstanding) })), table(['Invoice', 'Due date', 'Outstanding', 'Ageing'], outstanding.map(row => [row.reference, shortDate(row.dueDate), asMoney(row.outstanding), overdue.includes(row) ? 'Overdue' : row.outstanding > 0 ? 'Current' : 'Settled']))),
    report('procurement', 'Procurement commitments', 'Procurement', `${project.purchaseOrders.length} purchase order(s) represent ${asMoney(total(project.purchaseOrders, 'total'))} in project commitments.`, [metric('Committed value', asMoney(total(project.purchaseOrders, 'total')), total(project.purchaseOrders, 'total')), metric('Orders', project.purchaseOrders.length), metric('Received', project.purchaseOrders.filter(row => row.status === 'Received').length), metric('Open', project.purchaseOrders.filter(row => !['Received', 'Cancelled'].includes(row.status)).length)], project.purchaseOrders.map(row => ({ label: row.supplier, value: row.total, display: asMoney(row.total) })), table(['PO', 'Supplier', 'Order date', 'Value', 'Status'], project.purchaseOrders.map(row => [row.reference, row.supplier, shortDate(row.orderDate), asMoney(row.total), row.status]))),
    report('payables', 'Supplier payables', 'Procurement', `${asMoney(payable)} is outstanding to project suppliers across ${payables.filter(row => n(row.amount) > n(row.paidAmount)).length} open invoice(s).`, [metric('Invoiced', asMoney(total(payables, 'amount')), total(payables, 'amount')), metric('Paid', asMoney(total(payables, 'paidAmount')), total(payables, 'paidAmount')), metric('Outstanding', asMoney(payable), payable), metric('Supplier invoices', payables.length)], payables.map(row => ({ label: row.supplier, value: n(row.amount) - n(row.paidAmount), display: asMoney(n(row.amount) - n(row.paidAmount)) })), table(['Invoice', 'Supplier', 'Due', 'Value', 'Paid', 'Status'], payables.map(row => [row.invoiceNo, row.supplier, shortDate(row.dueDate), asMoney(row.amount), asMoney(row.paidAmount), row.status]))),
    report('programme', 'Programme progress', 'Delivery', `Overall delivery is ${project.progress}%. ${completedMilestones} of ${project.milestones.length} programme milestones are complete.`, [metric('Overall progress', `${project.progress}%`, project.progress), metric('Milestones', project.milestones.length), metric('Completed', completedMilestones), metric('Delayed', project.milestones.filter(row => row.status === 'Delayed').length)], milestoneStates.map(row => ({ ...row, display: `${row.value}` })), table(['Milestone', 'Due date', 'Status', 'Completed'], project.milestones.map(row => [row.title, shortDate(row.dueDate), row.status, shortDate(row.completedAt)]))),
    report('tasks', 'Task productivity', 'Delivery', `${completedTasks} of ${project.tasks.length} project tasks are complete or approved. ${project.tasks.filter(row => row.status === 'Blocked').length} task(s) are currently blocked.`, [metric('Total tasks', project.tasks.length), metric('Delivered', completedTasks), metric('Open', project.tasks.length - completedTasks), metric('Completion', `${pct(completedTasks, project.tasks.length)}%`, completedTasks)], taskStates.map(row => ({ ...row, display: `${row.value}` })), table(['Task', 'Owner', 'Due', 'Priority', 'Status'], project.tasks.map(row => [row.title, row.assignee, row.due, row.priority, row.status]))),
    report('labour', 'Labour and attendance', 'Resources', `${attendancePeople} worker-presence entries are recorded across ${new Set(attendance.map(row => String(row.date).slice(0, 10))).size} working day(s).`, [metric('Presence entries', attendancePeople), metric('Working days', new Set(attendance.map(row => String(row.date).slice(0, 10))).size), metric('Team members', project.team.length), metric('Attendance states', new Set(attendance.map(row => row.state)).size)], countBy(attendance, 'state').map(row => ({ ...row, display: `${row.value} entries` })), table(['Date', 'State', 'People', 'First in', 'Last out'], attendance.map(row => [shortDate(row.date), row.state, row.people, row.firstIn || '—', row.lastOut || '—']))),
    report('site-operations', 'Daily site operations', 'Site', `${siteReports.length} recent daily report(s) describe site production, workforce, weather and issues. The latest entry recorded ${siteReports[0]?.workforce || 0} people.`, [metric('Reports', siteReports.length), metric('Latest workforce', siteReports[0]?.workforce || 0), metric('Issues raised', issues.length), metric('Delay hours', delayHours)], siteReports.map(row => ({ label: shortDate(row.reportDate), value: row.workforce, display: `${row.workforce} people` })), table(['Date', 'Supervisor', 'Workforce', 'Work completed', 'Issue'], siteReports.map(row => [shortDate(row.reportDate), row.supervisor, row.workforce, row.workCompleted, row.issue || 'None']))),
    report('delays', 'Delay and disruption', 'Site', `${delayHours} delay hour(s) and ${issues.length} issue-bearing daily report(s) are recorded in the current reporting history.`, [metric('Delay hours', `${delayHours}h`, delayHours), metric('Reports with issues', issues.length), metric('Clear reports', siteReports.length - issues.length), metric('Delay days', siteReports.filter(row => n(row.delayHours) > 0).length)], siteReports.map(row => ({ label: shortDate(row.reportDate), value: row.delayHours, display: `${n(row.delayHours)}h` })), table(['Date', 'Delay', 'Weather', 'Issue', 'Supervisor'], siteReports.map(row => [shortDate(row.reportDate), `${n(row.delayHours)}h`, row.weather || '—', row.issue || 'No issue', row.supervisor]))),
    report('weather', 'Weather impact', 'Site', `${weather.length} weather condition(s) appear in the daily site history. Use the report alongside delays to identify recurring production impacts.`, [metric('Conditions', weather.length), metric('Report days', siteReports.length), metric('Delay hours', `${delayHours}h`, delayHours), metric('Most common', weather.sort((a, b) => b.value - a.value)[0]?.label || '—')], weather.map(row => ({ ...row, display: `${row.value} day(s)` })), table(['Weather', 'Reported days', 'Share'], weather.map(row => [row.label, row.value, `${pct(row.value, siteReports.length)}%`]))),
    report('materials', 'Material consumption', 'Resources', `${materials.length} material type(s) have been issued to this project. Quantities retain their operational units for accurate site control.`, [metric('Materials used', materials.length), metric('Issue movements', total(materials, 'movements')), metric('Top material', materials[0]?.name || '—'), metric('Top quantity', materials[0] ? `${n(materials[0].quantity).toLocaleString()} ${materials[0].unit}` : '—')], materials.map(row => ({ label: row.name, value: row.quantity, display: `${n(row.quantity).toLocaleString()} ${row.unit}` })), table(['Material', 'Quantity issued', 'Unit', 'Transactions'], materials.map(row => [row.name, n(row.quantity).toLocaleString(), row.unit, row.movements]))),
    report('equipment', 'Equipment deployment', 'Resources', `${equipment.length} equipment assignment(s) are linked to the project; ${equipment.filter(row => !row.returnedAt).length} remain deployed.`, [metric('Assignments', equipment.length), metric('Currently deployed', equipment.filter(row => !row.returnedAt).length), metric('Returned', equipment.filter(row => row.returnedAt).length), metric('Assets', new Set(equipment.map(row => row.code)).size)], countBy(equipment, row => row.returnedAt ? 'Returned' : 'Deployed'), table(['Equipment', 'Assigned to', 'From', 'Returned', 'Condition'], equipment.map(row => [`${row.code} · ${row.name}`, row.assignedTo, shortDate(row.assignedAt), shortDate(row.returnedAt), row.conditionNote || 'Not recorded']))),
    report('workforce', 'Project workforce allocation', 'Resources', `${project.team.length} employee(s) are currently allocated to the delivery team across ${new Set(project.team.map(row => row.projectRole)).size} project role(s).`, [metric('Team members', project.team.length), metric('Project roles', new Set(project.team.map(row => row.projectRole)).size), metric('Tasks', project.tasks.length), metric('Daily reports', siteReports.length)], countBy(project.team, 'projectRole').map(row => ({ ...row, display: `${row.value} people` })), table(['Employee', 'Code', 'Designation', 'Project role'], project.team.map(row => [row.name, row.code, row.designation, row.projectRole]))),
    report('documents', 'Document control', 'Governance', `${project.documents.length} document(s) are held in the project library alongside ${project.boqs.length} BOQ(s) and ${project.quotations.length} quotation(s).`, [metric('Documents', project.documents.length), metric('BOQs', project.boqs.length), metric('Quotations', project.quotations.length), metric('Commercial records', project.invoices.length + project.purchaseOrders.length)], [{ label: 'Files', value: project.documents.length }, { label: 'BOQs', value: project.boqs.length }, { label: 'Quotes', value: project.quotations.length }, { label: 'Invoices', value: project.invoices.length }], table(['Document', 'Category', 'Uploaded'], project.documents.map(row => [row.filename || row.title, row.category || row.docType || 'Project document', shortDate(row.createdAt)])))
  ];
}

function ReportVisual({ rows }) {
  const max = Math.max(1, ...rows.map(row => Math.abs(n(row.value))));
  return <div className="industrial-chart">{rows.slice(0, 14).map((row, index) => <div key={`${row.label}-${index}`}><span>{row.label}</span><i><b className={n(row.value) < 0 ? 'negative' : ''} style={{ width: `${Math.max(3, Math.abs(n(row.value)) / max * 100)}%` }} /></i><strong>{row.display ?? row.value}</strong></div>)}{!rows.length && <p>No recorded data is available for this visualization yet.</p>}</div>;
}

export default function ProjectReports({ project }) {
  const reports = useMemo(() => buildReports(project), [project]);
  const [selectedId, setSelectedId] = useState('profit-loss');
  const [query, setQuery] = useState('');
  const selected = reports.find(row => row.id === selectedId) || reports[0];
  const visible = reports.filter(row => `${row.title} ${row.category}`.toLowerCase().includes(query.toLowerCase()));
  const download = () => {
    const lines = [[selected.title], [selected.narrative], [], ...selected.metrics.map(row => [row.label, row.value]), [], selected.columns, ...selected.rows];
    const csv = lines.map(row => row.map(value => `"${String(value ?? '').replaceAll('"', '""')}"`).join(',')).join('\n');
    const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); const link = document.createElement('a');
    link.href = url; link.download = `${slug(project.name)}-${selected.id}-report.csv`; link.click(); URL.revokeObjectURL(url);
  };
  return <div className="industrial-reports">
    <aside className="report-library"><div className="report-library-head"><span>{reports.length} live reports</span><h2>Report library</h2><label><Search size={14} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Find a report" /></label></div><nav>{visible.map(report => <button className={selected.id === report.id ? 'active' : ''} onClick={() => setSelectedId(report.id)} key={report.id}><FileText size={15} /><span><strong>{report.title}</strong><small>{report.category}</small></span></button>)}</nav></aside>
    <section className="report-canvas">
      <header><div><span>{selected.category} report</span><h1>{selected.title}</h1><p>Live project data · generated {shortDate(new Date())}</p></div><button className="secondary" onClick={download}><Download size={15} />Export table</button></header>
      <article className={`report-narrative ${selected.id === 'profit-loss' && profitTone(selected)}`}><BarChart3 size={22} /><div><strong>Management interpretation</strong><p>{selected.narrative}</p></div></article>
      <div className="report-kpis">{selected.metrics.map((row, index) => <article key={row.label}><span>{row.label}</span><strong>{row.value}</strong>{index === 2 && row.raw < 0 ? <TrendingDown /> : <TrendingUp />}</article>)}</div>
      <section className="report-visual-panel"><div><span>Visual analysis</span><h2>Performance view</h2></div><ReportVisual rows={selected.visual} /></section>
      <section className="report-table-panel"><div><span>Supporting schedule</span><h2>Detailed records</h2></div><div className="report-table-scroll"><table><thead><tr>{selected.columns.map(column => <th key={column}>{column}</th>)}</tr></thead><tbody>{selected.rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell ?? '—'}</td>)}</tr>)}{!selected.rows.length && <tr><td colSpan={selected.columns.length}>No records have been entered for this report yet.</td></tr>}</tbody></table></div></section>
    </section>
  </div>;
}

const profitTone = selected => selected.metrics[2]?.raw < 0 ? 'loss' : 'profit';
